-- 대분류 생성
CREATE SEQUENCE SEQ_LCATEGORY_NO NOCACHE;
INSERT INTO LCATEGORY VALUES(SEQ_LCATEGORY_NO.NEXTVAL, '간편식사');
INSERT INTO LCATEGORY VALUES(SEQ_LCATEGORY_NO.NEXTVAL, '즉석조리');
INSERT INTO LCATEGORY VALUES(SEQ_LCATEGORY_NO.NEXTVAL, '과자류');
INSERT INTO LCATEGORY VALUES(SEQ_LCATEGORY_NO.NEXTVAL, '아이스크림');
INSERT INTO LCATEGORY VALUES(SEQ_LCATEGORY_NO.NEXTVAL, '식품');
INSERT INTO LCATEGORY VALUES(SEQ_LCATEGORY_NO.NEXTVAL, '음료');
INSERT INTO LCATEGORY VALUES(SEQ_LCATEGORY_NO.NEXTVAL, '생활용품');

-- 소분류 생성
CREATE SEQUENCE SEQ_SCATEGORY_NO NOCACHE;
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '도시락', 1);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '샌드위치/햄버거', 1);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '주먹밥/김밥', 1);

INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '튀김류', 2);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '베이커리', 2);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '즉석커피', 2);

INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '스낵/비스켓', 3);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '빵/디저트', 3);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '껌/초콜릿/캔디', 3);

INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '아이스크림', 4);

INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '가공식사', 5);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '안주류', 5);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '식재료', 5);

INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '음료', 6);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '아이스드링크', 6);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '유제품', 6);

INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '취미/레저', 7);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '의약외품', 7);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '신변잡화', 7);
INSERT INTO SCATEGORY VALUES(SEQ_SCATEGORY_NO.NEXTVAL, '생활잡화', 7);

-- 상품 등록
CREATE SEQUENCE SEQ_GOODS_NO NOCACHE;
INSERT INTO GOODS VALUES(SEQ_GOODS_NO.NEXTVAL, '자이언트머스타드치킨', DEFAULT, 1, 1);
