CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	NVARCHAR2(15)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(30)		NOT NULL,
	"MEMBER_NAME"	NVARCHAR2(20)		NOT NULL,
	"MEMBER_ADDRESS"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NOT NULL,
	"MEMBER_PROFILE"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL,
	"MEMBER_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"TEAM_NO"	NUMBER		NULL,
	"DEPARTMENT_NO"	NUMBER		NULL,
	"GRADE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '시퀀스';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '휴대폰 번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_PROFILE" IS '프로필 이미지';

COMMENT ON COLUMN "MEMBER"."MEMBER_AUTHORITY" IS '0 : 관리자, 1 : 회원';

COMMENT ON COLUMN "MEMBER"."MEMBER_ENROLL_DATE" IS '가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS 'N : 탈퇴 안함 Y : 탈퇴함';

COMMENT ON COLUMN "MEMBER"."TEAM_NO" IS '팀 코드 번호';

COMMENT ON COLUMN "MEMBER"."DEPARTMENT_NO" IS '부서 코드 번호';

COMMENT ON COLUMN "MEMBER"."GRADE_NO" IS '직급 코드 번호';

CREATE TABLE "DEPARTMENT" (
	"DEPARTMENT_NO"	NUMBER		NOT NULL,
	"DEPARTMENT_NAME"	NVARCHAR2(40)		NOT NULL
);

COMMENT ON COLUMN "DEPARTMENT"."DEPARTMENT_NO" IS '부서 코드 번호';

COMMENT ON COLUMN "DEPARTMENT"."DEPARTMENT_NAME" IS '부서 이름';

CREATE TABLE "GRADE" (
	"GRADE_NO"	NUMBER		NOT NULL,
	"GRADE_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "GRADE"."GRADE_NO" IS '직급 코드 번호';

COMMENT ON COLUMN "GRADE"."GRADE_NAME" IS '직급 이름';

CREATE TABLE "AUTH_KEY" (
	"AUTH_KEY_NO"	NUMBER		NOT NULL,
	"AUTH_KEY_EMAIL"	NVARCHAR2(30)		NOT NULL,
	"AUTH_KEY_SERIAL"	NVARCHAR2(30)		NOT NULL,
	"AUTH_KEY_TIME"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_NO" IS '인증키 번호';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_EMAIL" IS '이메일 주소';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_SERIAL" IS '인증키';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_TIME" IS '인증코드 생성시간';

CREATE TABLE "STORE" (
	"STORE_NO"	NUMBER		NOT NULL,
	"STORE_NAME"	NVARCHAR2(50)		NOT NULL,
	"STORE_ADDRESS"	NVARCHAR2(150)		NOT NULL,
	"STORE_TEL"	CHAR(10)		NOT NULL,
	"STORE_RUN_FL"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"STORE_OPEN_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STORE_CLOSE_DATE"	DATE		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "STORE"."STORE_NO" IS '점포 번호';

COMMENT ON COLUMN "STORE"."STORE_NAME" IS '점포 이름';

COMMENT ON COLUMN "STORE"."STORE_ADDRESS" IS '점포 주소';

COMMENT ON COLUMN "STORE"."STORE_TEL" IS '점포 번호(-빼고)';

COMMENT ON COLUMN "STORE"."STORE_RUN_FL" IS '운영여부';

COMMENT ON COLUMN "STORE"."STORE_OPEN_DATE" IS '개점일';

COMMENT ON COLUMN "STORE"."STORE_CLOSE_DATE" IS '폐점일';

COMMENT ON COLUMN "STORE"."MEMBER_NO" IS '시퀀스';

CREATE TABLE "GOODS" (
	"GOODS_NO"	NUMBER		NOT NULL,
	"GOODS_NAME"	NVARCHAR2(100)		NOT NULL,
	"GOODS_STANDARD"	NVARCHAR2(30)		NULL,
	"LCATEGORY_NO"	NUMBER		NOT NULL,
	"SCATEGORY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "GOODS"."GOODS_NO" IS '재고 번호';

COMMENT ON COLUMN "GOODS"."GOODS_NAME" IS '재고명';

COMMENT ON COLUMN "GOODS"."GOODS_STANDARD" IS '재고 규격';

COMMENT ON COLUMN "GOODS"."LCATEGORY_NO" IS '대분류 번호';

COMMENT ON COLUMN "GOODS"."SCATEGORY_NO" IS '소분류 번호';

CREATE TABLE "ORDER" (
	"ORDER_NO"	NUMBER		NOT NULL,
	"ORDER_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ORDER_AMOUNT"	NUMBER		NOT NULL,
	"STORE_NO"	NUMBER		NOT NULL,
	"GOODS_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ORDER"."ORDER_NO" IS '발주 번호';

COMMENT ON COLUMN "ORDER"."ORDER_DATE" IS '발주 날짜';

COMMENT ON COLUMN "ORDER"."ORDER_AMOUNT" IS '발주 수량';

COMMENT ON COLUMN "ORDER"."STORE_NO" IS '점포 번호';

COMMENT ON COLUMN "ORDER"."GOODS_NO" IS '재고 번호';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	CLOB		NOT NULL,
	"BOARD_ATTACH"	NVARCHAR2(50)		NULL,
	"BOARD_HITS"	NUMBER	DEFAULT 0	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_CODE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시판 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시판 내용';

COMMENT ON COLUMN "BOARD"."BOARD_ATTACH" IS '첨부파일';

COMMENT ON COLUMN "BOARD"."BOARD_HITS" IS '조회수';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '시퀀스';

COMMENT ON COLUMN "BOARD"."BOARD_CODE_NO" IS '게시판 코드';

CREATE TABLE "BOARD_CODE" (
	"BOARD_CODE_NO"	NUMBER		NOT NULL,
	"BOARD_CODE_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_CODE"."BOARD_CODE_NO" IS '게시판 코드';

COMMENT ON COLUMN "BOARD_CODE"."BOARD_CODE_NAME" IS '게시판 이름';

CREATE TABLE "BOARD_IMAGE" (
	"BOARD_IMAGE_NO"	NUMBER		NOT NULL,
	"BOARD_IMAGE_RENAME"	NVARCHAR2(50)		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMAGE"."BOARD_IMAGE_NO" IS '게시판 사진 번호';

COMMENT ON COLUMN "BOARD_IMAGE"."BOARD_IMAGE_RENAME" IS '사진 등록 이름 변경';

COMMENT ON COLUMN "BOARD_IMAGE"."BOARD_NO" IS '게시판 번호';

CREATE TABLE "BOOKMARK" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOOKMARK"."MEMBER_NO" IS '시퀀스';

COMMENT ON COLUMN "BOOKMARK"."BOARD_NO" IS '게시판 번호';

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"REPORT_TITLE"	NVARCHAR2(50)		NOT NULL,
	"REPORT_CONTENT"	NVARCHAR2(200)		NOT NULL,
	"REPORT_KIND"	NVARCHAR2(20)		NOT NULL,
	"REPORT_CONTENT_NO"	NUMBER		NOT NULL,
	"REPORT_ANSWER"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"REPORT_LOCATION"	NVARCHAR2(50)		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고 번호';

COMMENT ON COLUMN "REPORT"."MEMBER_NO" IS '시퀀스';

COMMENT ON COLUMN "REPORT"."REPORT_TITLE" IS '신고 제목';

COMMENT ON COLUMN "REPORT"."REPORT_CONTENT" IS '신고 내용';

COMMENT ON COLUMN "REPORT"."REPORT_KIND" IS '신고 종류';

COMMENT ON COLUMN "REPORT"."REPORT_CONTENT_NO" IS '신고 대상 번호';

COMMENT ON COLUMN "REPORT"."REPORT_ANSWER" IS '신고 처리 여부';

COMMENT ON COLUMN "REPORT"."REPORT_LOCATION" IS '신고 대상 주소';

COMMENT ON COLUMN "REPORT"."BOARD_NO" IS '게시글 번호';

CREATE TABLE "BOARD_COMMENT" (
	"BOARD_COMMENT_NO"	NUMBER		NOT NULL,
	"BOARD_COMMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_COMMENT_CONTENT"	NVARCHAR2(200)		NOT NULL,
	"BOARD_COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_COMMENT_PARENT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_COMMENT"."BOARD_COMMENT_NO" IS '댓글 번호';

COMMENT ON COLUMN "BOARD_COMMENT"."BOARD_COMMENT_DATE" IS '댓글 등록일';

COMMENT ON COLUMN "BOARD_COMMENT"."BOARD_COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "BOARD_COMMENT"."BOARD_COMMENT_DEL_FL" IS '댓글 삭제 여부';

COMMENT ON COLUMN "BOARD_COMMENT"."BOARD_NO" IS '게시판 번호';

COMMENT ON COLUMN "BOARD_COMMENT"."BOARD_COMMENT_PARENT" IS '댓글 번호';

CREATE TABLE "CHAT" (
	"CHAT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"CHAT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHAT_OPEN_MEMBER"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHAT"."CHAT_NO" IS '채팅방 번호';

COMMENT ON COLUMN "CHAT"."MEMBER_NO" IS '참여자 회원 번호';

COMMENT ON COLUMN "CHAT"."CHAT_DATE" IS '채팅방 생성 날짜';

COMMENT ON COLUMN "CHAT"."CHAT_OPEN_MEMBER" IS '채팅방 개설자 회원번호';

CREATE TABLE "CHAT_MESSAGE" (
	"CHAT_MESSAGE_NO"	NUMBER		NOT NULL,
	"CHAT_MESSAGE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHAT_MESSAGE_CONTENT"	NVARCHAR2(150)		NOT NULL,
	"CHAT_MESSAGE_READ"	NVARCHAR2(4)	DEFAULT '읽지않음'	NOT NULL,
	"CHAT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHAT_MESSAGE"."CHAT_MESSAGE_NO" IS '채팅 메시지 번호';

COMMENT ON COLUMN "CHAT_MESSAGE"."CHAT_MESSAGE_DATE" IS '메시지 보낸 시간';

COMMENT ON COLUMN "CHAT_MESSAGE"."CHAT_MESSAGE_CONTENT" IS '채팅 메시지 내용';

COMMENT ON COLUMN "CHAT_MESSAGE"."CHAT_MESSAGE_READ" IS '메시지 읽음 여부';

COMMENT ON COLUMN "CHAT_MESSAGE"."CHAT_NO" IS '채팅방 번호';

COMMENT ON COLUMN "CHAT_MESSAGE"."MEMBER_NO" IS '참여자 회원 번호';

CREATE TABLE "CHAT_IMAGE" (
	"CHAT_IMAGE_NO"	NUMBER		NOT NULL,
	"CHAT_IMAGE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHAT_IMAGE_ROUTE"	NVARCHAR2(50)		NOT NULL,
	"CHAT_IMAGE_ONAME"	NVARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "CHAT_IMAGE"."CHAT_IMAGE_NO" IS '채팅 이미지 번호';

COMMENT ON COLUMN "CHAT_IMAGE"."CHAT_IMAGE_DATE" IS '이미지 업로드 날짜';

COMMENT ON COLUMN "CHAT_IMAGE"."CHAT_IMAGE_ROUTE" IS '채팅 이미지 경로';

COMMENT ON COLUMN "CHAT_IMAGE"."CHAT_IMAGE_ONAME" IS '이미지 원본 이름';

CREATE TABLE "CHAT_FILE" (
	"CHAT_FILE_NO"	NUMBER		NOT NULL,
	"CHAT_UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHAT_FILE_ROUTE"	NVARCHAR2(50)		NOT NULL,
	"CHAT_FILE_ONAME"	NVARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "CHAT_FILE"."CHAT_FILE_NO" IS '채팅 파일 번호';

COMMENT ON COLUMN "CHAT_FILE"."CHAT_UPLOAD_DATE" IS '파일 업로드 날짜';

COMMENT ON COLUMN "CHAT_FILE"."CHAT_FILE_ROUTE" IS '채팅 파일 경로';

COMMENT ON COLUMN "CHAT_FILE"."CHAT_FILE_ONAME" IS '파일 원본 이름';

CREATE TABLE "APPROVAL" (
	"APPROVAL_NO"	NUMBER		NOT NULL,
	"APPROVAL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"APPROVAL_TITLE"	NVARCHAR2(50)		NOT NULL,
	"APPROVAL_CONTENT"	NVARCHAR2(1000)		NOT NULL,
	"APPROVAL_CONDITION"	NUMBER		NOT NULL,
	"APPROVAL_RETURN_COMMENT"	NVARCHAR2(300)		NOT NULL,
	"APPROVAL_DELETE"	NUMBER	DEFAULT 0	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"DEPARTMENT_NO"	NUMBER		NULL,
	"DOC_CATEGORY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "APPROVAL"."APPROVAL_NO" IS '기안된 전자결재 문서 번호';

COMMENT ON COLUMN "APPROVAL"."APPROVAL_DATE" IS '전자결재 결재요청 일자';

COMMENT ON COLUMN "APPROVAL"."APPROVAL_TITLE" IS '전자결재 제목';

COMMENT ON COLUMN "APPROVAL"."APPROVAL_CONTENT" IS '전자결재 내용';

COMMENT ON COLUMN "APPROVAL"."APPROVAL_CONDITION" IS '0: 결재중  1:임시저장  2:회수문서함 3:반려문서함 4:결재완료';

COMMENT ON COLUMN "APPROVAL"."APPROVAL_RETURN_COMMENT" IS '결재자의 반려 사유 코멘트';

COMMENT ON COLUMN "APPROVAL"."APPROVAL_DELETE" IS '0: 정상 1:30일 기한 지나 삭제됨 2:임시저장/회수/반려문서 기안자가 삭제';

COMMENT ON COLUMN "APPROVAL"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "APPROVAL"."DEPARTMENT_NO" IS '협조부서 코드 번호(1부서만 선택가능)';

COMMENT ON COLUMN "APPROVAL"."DOC_CATEGORY_NO" IS '0: 복무-휴가, 1: 인사-퇴직, 2: 업무-출점, 3: 업무-폐점, 4: 업무-지출, 5: 업무-발주';

CREATE TABLE "MESSAGE" (
	"MESSAGE_NO"	NUMBER		NOT NULL,
	"MESSAGE_CONTENT"	NVARCHAR2(200)		NOT NULL,
	"MESSAGE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MESSAGE_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO_SENDER"	NUMBER		NOT NULL,
	"MESSAGE_READ_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO_RECIPIENT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS '쪽지 번호';

COMMENT ON COLUMN "MESSAGE"."MESSAGE_CONTENT" IS '쪽지 내용';

COMMENT ON COLUMN "MESSAGE"."MESSAGE_DATE" IS '쪽지 보낸 시간';

COMMENT ON COLUMN "MESSAGE"."MESSAGE_DEL_FL" IS '삭제 여부';

COMMENT ON COLUMN "MESSAGE"."MEMBER_NO_SENDER" IS '발신자 번호';

COMMENT ON COLUMN "MESSAGE"."MESSAGE_READ_FL" IS '읽음 여부';

COMMENT ON COLUMN "MESSAGE"."MEMBER_NO_RECIPIENT" IS '수신자  번호';

CREATE TABLE "TEAM" (
	"TEAM_NO"	NUMBER		NOT NULL,
	"TEAM_NAME"	NVARCHAR2(40)		NOT NULL
);

COMMENT ON COLUMN "TEAM"."TEAM_NO" IS '팀 코드 번호';

COMMENT ON COLUMN "TEAM"."TEAM_NAME" IS '팀 이름';

CREATE TABLE "HISTORY" (
	"HISTORY_NO"	NUMBER		NOT NULL,
	"HISTORY_DIVIDE"	NVARCHAR2(2)		NOT NULL,
	"HISTORY_AMOUNT"	NUMBER		NOT NULL,
	"HISTORY_ACTUAL_PRICE"	NUMBER		NOT NULL,
	"HISTORY_UNIT_PRICE"	NUMBER		NOT NULL,
	"HISTORY_DISCOUNT"	NUMBER		NULL,
	"HISTORY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"HISTORY_STORE_NAME"	NVARCHAR2(50)		NOT NULL,
	"HISTORY_GOODS_NAME"	NVARCHAR2(50)		NOT NULL,
	"STORE_NO"	NUMBER		NOT NULL,
	"STOCK_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "HISTORY"."HISTORY_NO" IS '입출고 내역 번호';

COMMENT ON COLUMN "HISTORY"."HISTORY_DIVIDE" IS '입고인지 출고인지 알려주는 구분';

COMMENT ON COLUMN "HISTORY"."HISTORY_AMOUNT" IS '입출고 수량';

COMMENT ON COLUMN "HISTORY"."HISTORY_ACTUAL_PRICE" IS '실제 거래된 당시 출고단가에 할인율 적용';

COMMENT ON COLUMN "HISTORY"."HISTORY_UNIT_PRICE" IS '출고 될 때 그 당시 가격';

COMMENT ON COLUMN "HISTORY"."HISTORY_DISCOUNT" IS '출고 될 때 적용되어 있는 할인율';

COMMENT ON COLUMN "HISTORY"."HISTORY_DATE" IS '입출고 내역 날짜';

COMMENT ON COLUMN "HISTORY"."HISTORY_STORE_NAME" IS 'SELECT 성능 향상을 위한 반정규화 (JOIN 안하기 위해서)';

COMMENT ON COLUMN "HISTORY"."HISTORY_GOODS_NAME" IS 'SELECT 성능 향상을 위한 반정규화 (JOIN 안하기 위해서)';

COMMENT ON COLUMN "HISTORY"."STORE_NO" IS '점포 번호';

COMMENT ON COLUMN "HISTORY"."STOCK_NO" IS '재고 번호';

CREATE TABLE "STOCK" (
	"STORE_NO"	NUMBER		NOT NULL,
	"GOODS_NO"	NUMBER		NOT NULL,
	"STOCK_AMOUNT"	NUMBER		NOT NULL,
	"STOCK_DISCOUNT"	NUMBER		NULL,
	"STOCK_OUT_PRICE"	NUMBER		NOT NULL,
	"STOCK_IN_PRICE"	NUMBER		NULL
);

COMMENT ON COLUMN "STOCK"."STORE_NO" IS '점포 번호';

COMMENT ON COLUMN "STOCK"."GOODS_NO" IS '재고 번호';

COMMENT ON COLUMN "STOCK"."STOCK_AMOUNT" IS '점포 상품 수량';

COMMENT ON COLUMN "STOCK"."STOCK_DISCOUNT" IS '상품 할인율';

COMMENT ON COLUMN "STOCK"."STOCK_OUT_PRICE" IS '판매 가격';

COMMENT ON COLUMN "STOCK"."STOCK_IN_PRICE" IS '입고가';

CREATE TABLE "CALENDAR" (
	"CAL_NO"	NUMBER		NOT NULL,
	"CAL_ALLDAY"	NVARCHAR2(1)	DEFAULT 'N'	NULL,
	"CAL_START_TIME"	DATE		NULL,
	"CAL_END_TIME"	DATE		NULL,
	"CAL_TITLE"	NVARCHAR2(200)		NOT NULL,
	"CAL_DETAIL"	NVARCHAR2(1000)		NOT NULL,
	"CAL_COLOR"	NVARCHAR2(30)		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CALENDAR"."CAL_NO" IS '시퀀스';

COMMENT ON COLUMN "CALENDAR"."CAL_ALLDAY" IS '종일 여부';

COMMENT ON COLUMN "CALENDAR"."MEMBER_NO" IS '시퀀스';

CREATE TABLE "APPROVER" (
	"APPROVER_NO"	NUMBER		NOT NULL,
	"APPROVER_ORDER"	NUMBER		NOT NULL,
	"APPROVER_CONDITION"	NUMBER		NOT NULL,
	"APPROVER_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"APPROVAL_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "APPROVER"."APPROVER_NO" IS '결재자리스트 식별번호(시퀀스)';

COMMENT ON COLUMN "APPROVER"."APPROVER_ORDER" IS '결재라인 순서(작은 번호일수록 우선 결재) / ex) 0:첫번째 결재자 1:두번째 결재자 2:세번째 승인자 3: 최종 승인자';

COMMENT ON COLUMN "APPROVER"."APPROVER_CONDITION" IS '0:미승인, 1:승인, 2:반려';

COMMENT ON COLUMN "APPROVER"."APPROVER_DATE" IS '반려/승인 날짜';

COMMENT ON COLUMN "APPROVER"."APPROVAL_NO" IS '기안된 전자결재 문서 번호(시퀀스)';

COMMENT ON COLUMN "APPROVER"."MEMBER_NO" IS '결재자의 회원번호';

CREATE TABLE "DOC_HOLIDAY" (
	"APPROVAL_NO"	NUMBER		NOT NULL,
	"DOC_HOLIDAY_START"	DATE		NOT NULL,
	"DOC_HOLIDAY_END"	DATE		NOT NULL
);

COMMENT ON COLUMN "DOC_HOLIDAY"."APPROVAL_NO" IS '기안된 전자결재 문서 번호';

COMMENT ON COLUMN "DOC_HOLIDAY"."DOC_HOLIDAY_START" IS '휴가 시작일';

COMMENT ON COLUMN "DOC_HOLIDAY"."DOC_HOLIDAY_END" IS '휴가 종료일';

CREATE TABLE "DOC_RETIREMENT" (
	"APPROVAL_NO"	NUMBER		NOT NULL,
	"DOC_RETIRE_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "DOC_RETIREMENT"."APPROVAL_NO" IS '기안된 전자결재 문서 번호';

COMMENT ON COLUMN "DOC_RETIREMENT"."DOC_RETIRE_DATE" IS '퇴직예정일';

CREATE TABLE "DOC_STORE" (
	"APPROVAL_NO"	NUMBER		NOT NULL,
	"DOC_STORE_STATE"	NUMBER		NOT NULL,
	"STORE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "DOC_STORE"."APPROVAL_NO" IS '기안된 전자결재 문서 번호';

COMMENT ON COLUMN "DOC_STORE"."DOC_STORE_STATE" IS '0: 출점 / 1:폐점';

COMMENT ON COLUMN "DOC_STORE"."STORE_NO" IS '점포 번호';

CREATE TABLE "DOC_ORDER" (
	"DOC_ORDER_NO"	NUMBER		NOT NULL,
	"DOC_ORDER_AMOUNT"	NUMBER		NOT NULL,
	"DOC_ORDER_UNIT_PRICE"	NUMBER		NOT NULL,
	"DOC_ORDER_PRICE"	NUMBER		NOT NULL,
	"APPROVAL_NO"	NUMBER		NOT NULL,
	"GOODS_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "DOC_ORDER"."DOC_ORDER_NO" IS '발주 번호';

COMMENT ON COLUMN "DOC_ORDER"."DOC_ORDER_AMOUNT" IS '발주 수량';

COMMENT ON COLUMN "DOC_ORDER"."DOC_ORDER_UNIT_PRICE" IS '발주품 단가';

COMMENT ON COLUMN "DOC_ORDER"."DOC_ORDER_PRICE" IS '발주품 금액';

COMMENT ON COLUMN "DOC_ORDER"."APPROVAL_NO" IS '기안된 전자결재 문서 번호';

COMMENT ON COLUMN "DOC_ORDER"."GOODS_NO" IS '재고 번호';

CREATE TABLE "DOC_CATEGORY" (
	"DOC_CATEGORY_NO"	NUMBER		NOT NULL,
	"DOC_HTML_NAME"	NVARCHAR2(50)		NULL,
	"DOC_CATEGORY_GROUP"	NVARCHAR2(10)		NOT NULL,
	"DOC_CATEGORY_SORT"	VARCHAR(255)		NOT NULL
);

COMMENT ON COLUMN "DOC_CATEGORY"."DOC_CATEGORY_NO" IS '0: 복무-휴가, 1: 인사-퇴직, 2: 업무-출점, 3: 업무-폐점, 4: 업무-지출, 5: 업무-발주';

COMMENT ON COLUMN "DOC_CATEGORY"."DOC_CATEGORY_GROUP" IS '복무/인사/업무';

COMMENT ON COLUMN "DOC_CATEGORY"."DOC_CATEGORY_SORT" IS '휴가/퇴직/출점/폐점/지출/발주';

CREATE TABLE "LCATEGORY" (
	"LCATEGORY_NO"	NUMBER		NOT NULL,
	"LCATEGORY_NAME"	NVARCHAR2(15)		NOT NULL
);

COMMENT ON COLUMN "LCATEGORY"."LCATEGORY_NO" IS '대분류 번호';

COMMENT ON COLUMN "LCATEGORY"."LCATEGORY_NAME" IS '대분류 이름';

CREATE TABLE "SCATEGORY" (
	"SCATEGORY_NO"	NUMBER		NOT NULL,
	"SCATEGORY_NAME"	NVARCHAR2(15)		NOT NULL
);

COMMENT ON COLUMN "SCATEGORY"."SCATEGORY_NO" IS '소분류 번호';

COMMENT ON COLUMN "SCATEGORY"."SCATEGORY_NAME" IS '소분류 이름';

CREATE TABLE "ANONYMOUS" (
	"ANONYMOUS_NO"	NUMBER		NOT NULL,
	"ANONYMOUS_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ANONYMOUS_CONTENT"	NVARCHAR2(300)		NOT NULL,
	"ANONYMOUS_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ANONYMOUS"."ANONYMOUS_NO" IS '익명 게시판 게시글 번호';

COMMENT ON COLUMN "ANONYMOUS"."ANONYMOUS_DATE" IS '익명 게시판 등록일';

COMMENT ON COLUMN "ANONYMOUS"."ANONYMOUS_CONTENT" IS '익명 게시판 내용';

COMMENT ON COLUMN "ANONYMOUS"."ANONYMOUS_DEL_FL" IS '익명 게시판 삭제 여부';

COMMENT ON COLUMN "ANONYMOUS"."MEMBER_NO" IS '시퀀스';

CREATE TABLE "APPROVAL_FILE" (
	"APPROVAL_FILE_NO"	NUMBER		NOT NULL,
	"APPROVAL_NO"	NUMBER		NOT NULL,
	"APPROVAL_FILE_ROUTE"	NVARCHAR2(100)		NULL
);

COMMENT ON COLUMN "APPROVAL_FILE"."APPROVAL_FILE_NO" IS '첨부파일번호(시퀀스)';

COMMENT ON COLUMN "APPROVAL_FILE"."APPROVAL_NO" IS '기안된 전자결재 문서 번호';

COMMENT ON COLUMN "APPROVAL_FILE"."APPROVAL_FILE_ROUTE" IS '전자결재 첨부파일 경로';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY (
	"DEPARTMENT_NO"
);

ALTER TABLE "GRADE" ADD CONSTRAINT "PK_GRADE" PRIMARY KEY (
	"GRADE_NO"
);

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
	"AUTH_KEY_NO"
);

ALTER TABLE "STORE" ADD CONSTRAINT "PK_STORE" PRIMARY KEY (
	"STORE_NO"
);

ALTER TABLE "GOODS" ADD CONSTRAINT "PK_GOODS" PRIMARY KEY (
	"GOODS_NO"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"ORDER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_CODE" ADD CONSTRAINT "PK_BOARD_CODE" PRIMARY KEY (
	"BOARD_CODE_NO"
);

ALTER TABLE "BOARD_IMAGE" ADD CONSTRAINT "PK_BOARD_IMAGE" PRIMARY KEY (
	"BOARD_IMAGE_NO"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "PK_BOOKMARK" PRIMARY KEY (
	"MEMBER_NO",
	"BOARD_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO",
	"MEMBER_NO"
);

ALTER TABLE "BOARD_COMMENT" ADD CONSTRAINT "PK_BOARD_COMMENT" PRIMARY KEY (
	"BOARD_COMMENT_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "PK_CHAT" PRIMARY KEY (
	"CHAT_NO",
	"MEMBER_NO"
);

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "PK_CHAT_MESSAGE" PRIMARY KEY (
	"CHAT_MESSAGE_NO"
);

ALTER TABLE "CHAT_IMAGE" ADD CONSTRAINT "PK_CHAT_IMAGE" PRIMARY KEY (
	"CHAT_IMAGE_NO"
);

ALTER TABLE "CHAT_FILE" ADD CONSTRAINT "PK_CHAT_FILE" PRIMARY KEY (
	"CHAT_FILE_NO"
);

ALTER TABLE "APPROVAL" ADD CONSTRAINT "PK_APPROVAL" PRIMARY KEY (
	"APPROVAL_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MESSAGE_NO"
);

ALTER TABLE "TEAM" ADD CONSTRAINT "PK_TEAM" PRIMARY KEY (
	"TEAM_NO"
);

ALTER TABLE "HISTORY" ADD CONSTRAINT "PK_HISTORY" PRIMARY KEY (
	"HISTORY_NO"
);

ALTER TABLE "STOCK" ADD CONSTRAINT "PK_STOCK" PRIMARY KEY (
	"STORE_NO",
	"GOODS_NO"
);

ALTER TABLE "CALENDAR" ADD CONSTRAINT "PK_CALENDAR" PRIMARY KEY (
	"CAL_NO"
);

ALTER TABLE "APPROVER" ADD CONSTRAINT "PK_APPROVER" PRIMARY KEY (
	"APPROVER_NO"
);

ALTER TABLE "DOC_HOLIDAY" ADD CONSTRAINT "PK_DOC_HOLIDAY" PRIMARY KEY (
	"APPROVAL_NO"
);

ALTER TABLE "DOC_RETIREMENT" ADD CONSTRAINT "PK_DOC_RETIREMENT" PRIMARY KEY (
	"APPROVAL_NO"
);

ALTER TABLE "DOC_STORE" ADD CONSTRAINT "PK_DOC_STORE" PRIMARY KEY (
	"APPROVAL_NO"
);

ALTER TABLE "DOC_ORDER" ADD CONSTRAINT "PK_DOC_ORDER" PRIMARY KEY (
	"DOC_ORDER_NO"
);

ALTER TABLE "DOC_CATEGORY" ADD CONSTRAINT "PK_DOC_CATEGORY" PRIMARY KEY (
	"DOC_CATEGORY_NO"
);

ALTER TABLE "LCATEGORY" ADD CONSTRAINT "PK_LCATEGORY" PRIMARY KEY (
	"LCATEGORY_NO"
);

ALTER TABLE "SCATEGORY" ADD CONSTRAINT "PK_SCATEGORY" PRIMARY KEY (
	"SCATEGORY_NO"
);

ALTER TABLE "ANONYMOUS" ADD CONSTRAINT "PK_ANONYMOUS" PRIMARY KEY (
	"ANONYMOUS_NO"
);

ALTER TABLE "APPROVAL_FILE" ADD CONSTRAINT "PK_APPROVAL_FILE" PRIMARY KEY (
	"APPROVAL_FILE_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_TEAM_TO_MEMBER_1" FOREIGN KEY (
	"TEAM_NO"
)
REFERENCES "TEAM" (
	"TEAM_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_DEPARTMENT_TO_MEMBER_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "DEPARTMENT" (
	"DEPARTMENT_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_GRADE_TO_MEMBER_1" FOREIGN KEY (
	"GRADE_NO"
)
REFERENCES "GRADE" (
	"GRADE_NO"
);

ALTER TABLE "STORE" ADD CONSTRAINT "FK_MEMBER_TO_STORE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "GOODS" ADD CONSTRAINT "FK_LCATEGORY_TO_GOODS_1" FOREIGN KEY (
	"LCATEGORY_NO"
)
REFERENCES "LCATEGORY" (
	"LCATEGORY_NO"
);

ALTER TABLE "GOODS" ADD CONSTRAINT "FK_SCATEGORY_TO_GOODS_1" FOREIGN KEY (
	"SCATEGORY_NO"
)
REFERENCES "SCATEGORY" (
	"SCATEGORY_NO"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_STORE_TO_ORDER_1" FOREIGN KEY (
	"STORE_NO"
)
REFERENCES "STORE" (
	"STORE_NO"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_GOODS_TO_ORDER_1" FOREIGN KEY (
	"GOODS_NO"
)
REFERENCES "GOODS" (
	"GOODS_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_CODE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_CODE_NO"
)
REFERENCES "BOARD_CODE" (
	"BOARD_CODE_NO"
);

ALTER TABLE "BOARD_IMAGE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMAGE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_MEMBER_TO_BOOKMARK_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_BOARD_TO_BOOKMARK_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_ANONYMOUS_TO_REPORT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "ANONYMOUS" (
	"ANONYMOUS_NO"
);

ALTER TABLE "BOARD_COMMENT" ADD CONSTRAINT "FK_BOARD_TO_BOARD_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "BOARD_COMMENT" ADD CONSTRAINT "FK_BOARD_COMMENT_TO_BOARD_COMMENT_1" FOREIGN KEY (
	"BOARD_COMMENT_PARENT"
)
REFERENCES "BOARD_COMMENT" (
	"BOARD_COMMENT_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "FK_CHAT_TO_CHAT_MESSAGE_1" FOREIGN KEY (
	"CHAT_NO"
)
REFERENCES "CHAT" (
	"CHAT_NO"
);

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "FK_CHAT_TO_CHAT_MESSAGE_2" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "CHAT" (
	"MEMBER_NO"
);

ALTER TABLE "APPROVAL" ADD CONSTRAINT "FK_MEMBER_TO_APPROVAL_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "APPROVAL" ADD CONSTRAINT "FK_DEPARTMENT_TO_APPROVAL_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "DEPARTMENT" (
	"DEPARTMENT_NO"
);

ALTER TABLE "APPROVAL" ADD CONSTRAINT "FK_DOC_CATEGORY_TO_APPROVAL_1" FOREIGN KEY (
	"DOC_CATEGORY_NO"
)
REFERENCES "DOC_CATEGORY" (
	"DOC_CATEGORY_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_MEMBER_TO_MESSAGE_1" FOREIGN KEY (
	"MEMBER_NO_SENDER"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_MEMBER_TO_MESSAGE_2" FOREIGN KEY (
	"MEMBER_NO_RECIPIENT"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "HISTORY" ADD CONSTRAINT "FK_STORE_TO_HISTORY_1" FOREIGN KEY (
	"STORE_NO"
)
REFERENCES "STORE" (
	"STORE_NO"
);

ALTER TABLE "HISTORY" ADD CONSTRAINT "FK_GOODS_TO_HISTORY_1" FOREIGN KEY (
	"STOCK_NO"
)
REFERENCES "GOODS" (
	"GOODS_NO"
);

ALTER TABLE "STOCK" ADD CONSTRAINT "FK_STORE_TO_STOCK_1" FOREIGN KEY (
	"STORE_NO"
)
REFERENCES "STORE" (
	"STORE_NO"
);

ALTER TABLE "STOCK" ADD CONSTRAINT "FK_GOODS_TO_STOCK_1" FOREIGN KEY (
	"GOODS_NO"
)
REFERENCES "GOODS" (
	"GOODS_NO"
);

ALTER TABLE "CALENDAR" ADD CONSTRAINT "FK_MEMBER_TO_CALENDAR_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "APPROVER" ADD CONSTRAINT "FK_APPROVAL_TO_APPROVER_1" FOREIGN KEY (
	"APPROVAL_NO"
)
REFERENCES "APPROVAL" (
	"APPROVAL_NO"
);

ALTER TABLE "APPROVER" ADD CONSTRAINT "FK_MEMBER_TO_APPROVER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "DOC_HOLIDAY" ADD CONSTRAINT "FK_APPROVAL_TO_DOC_HOLIDAY_1" FOREIGN KEY (
	"APPROVAL_NO"
)
REFERENCES "APPROVAL" (
	"APPROVAL_NO"
);

ALTER TABLE "DOC_RETIREMENT" ADD CONSTRAINT "FK_APPROVAL_TO_DOC_RETIREMENT_1" FOREIGN KEY (
	"APPROVAL_NO"
)
REFERENCES "APPROVAL" (
	"APPROVAL_NO"
);

ALTER TABLE "DOC_STORE" ADD CONSTRAINT "FK_APPROVAL_TO_DOC_STORE_1" FOREIGN KEY (
	"APPROVAL_NO"
)
REFERENCES "APPROVAL" (
	"APPROVAL_NO"
);

ALTER TABLE "DOC_STORE" ADD CONSTRAINT "FK_STORE_TO_DOC_STORE_1" FOREIGN KEY (
	"STORE_NO"
)
REFERENCES "STORE" (
	"STORE_NO"
);

ALTER TABLE "DOC_ORDER" ADD CONSTRAINT "FK_APPROVAL_TO_DOC_ORDER_1" FOREIGN KEY (
	"APPROVAL_NO"
)
REFERENCES "APPROVAL" (
	"APPROVAL_NO"
);

ALTER TABLE "DOC_ORDER" ADD CONSTRAINT "FK_GOODS_TO_DOC_ORDER_1" FOREIGN KEY (
	"GOODS_NO"
)
REFERENCES "GOODS" (
	"GOODS_NO"
);

ALTER TABLE "ANONYMOUS" ADD CONSTRAINT "FK_MEMBER_TO_ANONYMOUS_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "APPROVAL_FILE" ADD CONSTRAINT "FK_APPROVAL_TO_APPROVAL_FILE_1" FOREIGN KEY (
	"APPROVAL_NO"
)
REFERENCES "APPROVAL" (
	"APPROVAL_NO"
);

