
CREATE SEQUENCE SEQ_GOODS_NO NOCACHE;

INSERT INTO "GOODS"
VALUES (SEQ_GOODS_NO.NEXTVAL, '맛이따', '낱개', 1, 1);

ROLLBACK;

SELECT LCATEGORY_NO FROM LCATEGORY WHERE LCATEGORY_NAME = '아이스크림';

ORDER BY DESC;

DELETE FROM GOODS
WHERE GOODS_NO = 17;