/* 회원가입 시 시퀀스 넘버 생성 */
CREATE SEQUENCE SEQ_MEMBER_NO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 99999
NOCYCLE
NOCACHE
NOORDER;

COMMIT;

/* 관리자 계정 추가 */
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', 'admin01', 'admin@admin.com', '관리자1', '04540^^^서울시 중구 남대문로 120^^^2층',
'01012341234', NULL, 0, DEFAULT, DEFAULT, 8, 3, 5);


/* 점주 계정 */
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'manager1', '123123', 'manager1@admin.com', '점주1', '04540^^^서울시 중구 남대문로 120^^^3층',
'01012341234', NULL, 1, DEFAULT, DEFAULT, 11, 5, 6);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'manager2', '123123', 'manager2@admin.com', '점주2', '04540^^^서울시 중구 남대문로 120^^^4층',
'01012341234', NULL, 1, DEFAULT, DEFAULT, 11, 5, 6);

DELETE FROM "MEMBER" ;
COMMIT;




SELECT * FROM "MEMBER";


/* 관리자 계정 생성 확인 및 로그인 가능 여부 체크 */
SELECT MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_EMAIL, MEMBER_NAME, MEMBER_ADDRESS,
MEMBER_TEL, MEMBER_PROFILE, MEMBER_AUTHORITY, 
	TO_CHAR(MEMBER_ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') ENROLL_DATE
FROM "MEMBER"
WHERE MEMBER_DEL_FL = 'N'
		 AND MEMBER_ID = 'admin';