-- 전체 점포정보조회
SELECT STORE_NO , STORE_NAME , STORE_TEL , STORE_ADDRESS , STORE_RUN_FL , MEMBER_NO , MEMBER_NAME
FROM STORE
JOIN "MEMBER" USING (MEMBER_NO)
;

COMMIT;

SELECT COUNT(*)
FROM STORE s ;

-- 점포 등록
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '중구명동점', '서울 중구 퇴계로 114-1, 1 2층',
	'027131460', DEFAULT, DEFAULT, NULL, 7);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '명동화이자점', '서울 중구 퇴계로 105 (충무로1가)',
	'027131460', DEFAULT, DEFAULT, NULL, 10);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '남산쌍용점', '서울 중구 소공로 46 (회현동2가, 쌍용남산플래티넘) 쌍용남산플래티넘',
	'023161460', DEFAULT, DEFAULT, NULL, 11);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '종로센터점', '서울 종로구 종로 78 미려빌딩',
	'0214531460', DEFAULT, DEFAULT, NULL, 12);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '남산회현점', '서울 중구 퇴계로10길 20 (회현동1가)',
	'021231460', DEFAULT, DEFAULT, NULL, 13);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '한국은행점', '서울 중구 남대문로 39',
	'027131343', DEFAULT, DEFAULT, NULL, 14);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '마포환일길점', '서울 마포구 환일길 39 (아현동)',
	'023141460', DEFAULT, DEFAULT, NULL, 15);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '청구역점', '서울 중구 청구로 94 (신당동)',
	'0222326380', DEFAULT, DEFAULT, NULL, 16);
	