-- 전체 점포정보조회
SELECT STORE_NO , STORE_NAME , STORE_TEL , STORE_ADDRESS , STORE_RUN_FL , MEMBER_NO , MEMBER_NAME
FROM STORE
JOIN "MEMBER" USING (MEMBER_NO)
;

COMMIT;

SELECT COUNT(*)
FROM STORE s ;

-- 점포 등록
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '중구명동점', '서울 중구 퇴계로 114-1, 1 2층',
	'027131460', DEFAULT, DEFAULT, NULL, 7);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '명동화이자점', '서울 중구 퇴계로 105 (충무로1가)',
	'027131460', DEFAULT, DEFAULT, NULL, 10);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '남산쌍용점', '서울 중구 소공로 46 (회현동2가, 쌍용남산플래티넘) 쌍용남산플래티넘',
	'023161460', DEFAULT, DEFAULT, NULL, 11);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '종로센터점', '서울 종로구 종로 78 미려빌딩',
	'0214531460', DEFAULT, DEFAULT, NULL, 12);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '남산회현점', '서울 중구 퇴계로10길 20 (회현동1가)',
	'021231460', DEFAULT, DEFAULT, NULL, 13);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '한국은행점', '서울 중구 남대문로 39',
	'027131343', DEFAULT, DEFAULT, NULL, 14);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '마포환일길점', '서울 마포구 환일길 39 (아현동)',
	'023141460', DEFAULT, DEFAULT, NULL, 15);
	
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '청구역점', '서울 중구 청구로 94 (신당동)',
	'0222326380', DEFAULT, DEFAULT, NULL, 16);
<<<<<<< HEAD
	
=======
	



-- 검색어가 일치하는 점포정보조회
SELECT *
FROM STORE
JOIN "MEMBER" USING (MEMBER_NO)
WHERE STORE_NAME LIKE '%2%' OR
STORE_TEL LIKE '%2%' OR
STORE_ADDRESS LIKE '%2%' OR
MEMBER_NAME LIKE  '%2%'
;

-- 검색어가 일치하는 점포 갯수
SELECT COUNT(*) 
FROM STORE
JOIN "MEMBER" USING (MEMBER_NO)
WHERE STORE_NAME LIKE '%2%' OR
STORE_TEL LIKE '%2%' OR
STORE_ADDRESS LIKE '%2%' OR
MEMBER_NAME LIKE  '%2%'
;

-- 점포 운영상태 바꾸기
UPDATE STORE SET
STORE_RUN_FL = 'Y'
WHERE STORE_NO = 1;

ROLLBACK;

SELECT * FROM STORE; 
WHERE STORE_NO = 5;

-- 점포 인서트
INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '하둘셋넷다여일여아점', '서울 중구 청구로 94 (신당동)',
	'01023121235', DEFAULT, DEFAULT, NULL, 16);

INSERT INTO STORE
VALUES(SEQ_STORE_NO.NEXTVAL, '인서트테스트점', '서울시 중구 어쩌구저쩌구',
	'01012345678', DEFAULT, DEFAULT, NULL, NULL);


SELECT STORE_NO , STORE_NAME , STORE_TEL , STORE_ADDRESS , STORE_RUN_FL , NVL2(MEMBER_NO, '없음', MEMBER_NO) , NVL(MEMBER_NAME, '없음', MEMBER_NAME)
FROM STORE
JOIN "MEMBER" USING (MEMBER_NO)
ORDER BY STORE_NO;

-- 멤버넘버 없는 경우까지 포함하여 점포정보 얻어오기
SELECT STORE_NO, STORE_NAME, STORE_TEL, STORE_ADDRESS, STORE_RUN_FL, 
       CASE 
	       WHEN MEMBER_NO IS NULL
	       THEN NULL
	       ELSE MEMBER_NO
	   END MEMBER_NO,
       CASE
	       WHEN MEMBER_NO IS NOT NULL
	       THEN M.MEMBER_NAME
	    END MEMBER_NAME
FROM STORE
LEFT JOIN "MEMBER" M USING (MEMBER_NO)
ORDER BY STORE_NO
;

-- memberNo가 없는 경우에도 count가 될 수 있도록 하기
SELECT COUNT(*)
FROM STORE
LEFT JOIN "MEMBER" USING (MEMBER_NO)
WHERE STORE_NAME LIKE '%인서트%' OR
STORE_TEL LIKE '%인서트%' OR
STORE_ADDRESS LIKE '%인서트%' OR
MEMBER_NAME LIKE  '%인서트%';


UPDATE STORE SET
MEMBER_NO = 10
WHERE STORE_NO = 17;


ROLLBACK;

SELECT *
FROM "MEMBER"
WHERE MEMBER_NO = 21;

SELECT *
FROM STORE
WHERE MEMBER_NO = 21;

SELECT COUNT(*) 
FROM "MEMBER"
WHERE MEMBER_NO = 25;



COMMIT;

--점포명 중복검사
SELECT COUNT(*) 
FROM STORE
WHERE STORE_RUN_FL = 'Y' AND
STORE_NAME = '서울시구가지점'
;

-- 점포전화번호 중복검사
SELECT COUNT(*) 
FROM STORE
WHERE STORE_TEL = '027131460';

-- 점포 주소 중복검사
SELECT COUNT(*) 
FROM STORE
WHERE STORE_ADDRESS = '서울 중구 퇴계로 105 (충무로1가)'
;


--점포 정보 업데이트
UPDATE STORE SET
STORE_NAME = '반송그리점',
MEMBER_NO = 26,
STORE_TEL = '0104628501',
STORE_ADDRESS ='점포정보수정테스트중 주소입니다'
WHERE STORE_NO = 10
;

SELECT * FROM STORE s ;
WHERE STORE_NO =10;

COMMIT;
ROLLBACK;

SELECT * 
FROM "MEMBER"
JOIN STORE USING (MEMBER_NO)
WHERE MEMBER_NO = 16;

-- 점주명 정보 수정
UPDATE "MEMBER" SET
MEMBER_NAME = '수정된점주명'
WHERE MEMBER_NO = 26;

-- 회원정보 INSERT test
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'test', '123123', '123@admin.com', '테스트임', '주소주소주소주소',
'01012312234', NULL, 1, DEFAULT, DEFAULT, 11, 5, 6);
COMMIT;

MERGE INTO STORE S
USING MEMBER M ON (S.MEMBER_NO = M.MEMBER_NO)
WHEN MATCHED THEN
	
ALTER TABLE STORE;



-- 점포번호순 정렬
SELECT STORE_NO, STORE_NAME, STORE_TEL, STORE_ADDRESS, STORE_RUN_FL, 
       CASE 
	       WHEN MEMBER_NO IS NULL
	       THEN NULL
	       ELSE MEMBER_NO
	   END MEMBER_NO,
       CASE
	       WHEN MEMBER_NO IS NOT NULL
	       THEN M.MEMBER_NAME
	    END MEMBER_NAME
FROM STORE
LEFT JOIN "MEMBER" M USING (MEMBER_NO)
		WHERE STORE_NAME LIKE '%%' OR
		STORE_TEL LIKE '%%' OR
		STORE_ADDRESS LIKE '%%' OR
		MEMBER_NAME LIKE  '%%'
ORDER BY STORE_NO
;


--점포명순 정렬
SELECT STORE_NO, STORE_NAME, STORE_TEL, STORE_ADDRESS, STORE_RUN_FL, 
   CASE 
       WHEN MEMBER_NO IS NULL
       THEN NULL
       ELSE MEMBER_NO
   END MEMBER_NO,
   CASE
       WHEN MEMBER_NO IS NOT NULL
       THEN M.MEMBER_NAME
    END MEMBER_NAME
FROM STORE
LEFT JOIN "MEMBER" M USING (MEMBER_NO)
WHERE STORE_NAME LIKE '%%' OR
STORE_TEL LIKE '%%' OR
STORE_ADDRESS LIKE '%%' OR
MEMBER_NAME LIKE  '%%'
ORDER BY STORE_NAME;


-- 점포테이블에 runApproval(폐점승인여부) 컬럼 추가
ALTER TABLE STORE
ADD STORE_RUN_APPROVAL CHAR(1) DEFAULT 'N' CHECK (STORE_RUN_APPROVAL IN ('Y', 'N'));

ALTER TABLE STORE
DROP COLUMN STORE_RUN_APPROVAL;



-- 폐점승인여부 승인시(Y) 점포운영상태 폐쇄(N)로 바꾸는 트리거
CREATE TRIGGER TRG_STORE_RUN
AFTER UPDATE OF STORE_RUN_APPROVAL ON STORE
FOR EACH ROW
	BEGIN
		IF :NEW.STORE_RUN_APPROVAL = 'Y'
		THEN 
			UPDATE STORE SET STORE_RUN_FL = 'N'
			WHERE STORE_NO = :NEW.STORE_NO;
		END IF;
	END;

-- 작동댐!
CREATE OR REPLACE TRIGGER TRG_STORE_RUN
BEFORE UPDATE OF STORE_RUN_APPROVAL ON STORE
FOR EACH ROW
	BEGIN
	  IF :NEW.STORE_RUN_APPROVAL = 'Y' THEN
	     :NEW.STORE_RUN_FL := 'N';
	  END IF;
	END;



-- 트리거 활성화
ALTER TRIGGER TRG_STORE_RUN ENABLE;

DROP TRIGGER TRG_STORE_RUN;
	

-- 운영상태 바꾸기
UPDATE STORE SET
STORE_RUN_FL = 'N'
WHERE STORE_RUN_APPROVAL = 'Y';

COMMIT;

-- 운영폐쇄 트리거 테스트(폐점승인 시 자동 폐쇄)
UPDATE STORE SET
STORE_RUN_APPROVAL = 'Y'
WHERE STORE_NO = 3;

SELECT * FROM MEMBER;
-- 사장, 부사장 회원정보변경
UPDATE MEMBER SET
MEMBER_NAME = '윤성민'
WHERE MEMBER_NO =11;

-- 팀장 인서트
-- 인사관리부 직원 인서트
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'mate', '$2a$10$xlsemZtWCryE7fTgWUVVfemE2RnzTXp1mXvmjVq6hmmZHrp6vsuQi', '12@admin.com', '박정훈', '주소주소주소주소',
'01012312239', NULL, 1, DEFAULT, DEFAULT, 1, 1, 5);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'mate1', '$2a$10$xlsemZtWCryE7fTgWUVVfemE2RnzTXp1mXvmjVq6hmmZHrp6vsuQi', '12@admin.com', '김상철', '주소주소주소주소',
'01012312239', NULL, 1, DEFAULT, DEFAULT, 2, 1, 5);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'mate2', '$2a$10$xlsemZtWCryE7fTgWUVVfemE2RnzTXp1mXvmjVq6hmmZHrp6vsuQi', '12@admin.com', '유상관', '주소주소주소주소',
'01012312239', NULL, 1, DEFAULT, DEFAULT, 3, 1, 5);

-- 경영관리부 직원 인서트
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'mate3', '$2a$10$xlsemZtWCryE7fTgWUVVfemE2RnzTXp1mXvmjVq6hmmZHrp6vsuQi', '12@admin.com', '최한울', '주소주소주소주소',
'01012312236', NULL, 1, DEFAULT, DEFAULT, 4, 2, 5);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'mate4', '$2a$10$xlsemZtWCryE7fTgWUVVfemE2RnzTXp1mXvmjVq6hmmZHrp6vsuQi', '12@admin.com', '이서', '주소주소주소주소',
'01012312236', NULL, 1, DEFAULT, DEFAULT, 5, 2, 5);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'mate5', '$2a$10$xlsemZtWCryE7fTgWUVVfemE2RnzTXp1mXvmjVq6hmmZHrp6vsuQi', '12@admin.com', '조상균', '주소주소주소주소',
'01012312236', NULL, 1, DEFAULT, DEFAULT, 6, 2, 5);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'mate6', '$2a$10$xlsemZtWCryE7fTgWUVVfemE2RnzTXp1mXvmjVq6hmmZHrp6vsuQi', '12@admin.com', '유정서', '주소주소주소주소',
'01012312236', NULL, 1, DEFAULT, DEFAULT, 7, 2, 5);

-- 운영관리부 직원 인서트
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'mate7', '$2a$10$xlsemZtWCryE7fTgWUVVfemE2RnzTXp1mXvmjVq6hmmZHrp6vsuQi', '12@admin.com', '김민준', '주소주소주소주소',
'01012312237', NULL, 1, DEFAULT, DEFAULT, 8, 3, 5);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'mate8', '$2a$10$xlsemZtWCryE7fTgWUVVfemE2RnzTXp1mXvmjVq6hmmZHrp6vsuQi', '12@admin.com', '이윤지', '주소주소주소주소',
'01012312237', NULL, 1, DEFAULT, DEFAULT, 9, 3, 5);

-- 고객관리부 직원 인서트
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'mate9', '$2a$10$xlsemZtWCryE7fTgWUVVfemE2RnzTXp1mXvmjVq6hmmZHrp6vsuQi', '12@admin.com', '윤정호', '주소주소주소주소',
'01012312238', NULL, 1, DEFAULT, DEFAULT, 10, 4, 5);

DELETE FROM "MEMBER"
WHERE MEMBER_NO = 78;


