-- 유진 sql


-- 문서분류 테이블 수정을 위한 DROP+CREATE 


DROP TABLE "DOC_CATEGORY" CASCADE CONSTRAINTS;

CREATE TABLE "DOC_CATEGORY" ( 
  "DOC_CATEGORY_NO"	NUMBER		NOT NULL,
  "DOC_HTML_NAME"	NVARCHAR2(50)		NULL,
  "DOC_CATEGORY_GROUP"	NVARCHAR2(10)		NOT NULL,
  "DOC_CATEGORY_SORT"	NVARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "DOC_CATEGORY"."DOC_CATEGORY_NO" IS '0: 복무-휴가, 1: 인사-퇴직, 2: 업무-출점, 3: 업무-폐점, 4: 업무-지출, 5: 업무-발주';

COMMENT ON COLUMN "DOC_CATEGORY"."DOC_CATEGORY_GROUP" IS '복무/인사/업무';

COMMENT ON COLUMN "DOC_CATEGORY"."DOC_CATEGORY_SORT" IS '휴가/퇴직/출점/폐점/지출/발주';

ALTER TABLE "DOC_CATEGORY" ADD CONSTRAINT "PK_DOC_CATEGORY" PRIMARY KEY (
  "DOC_CATEGORY_NO"
);

ALTER TABLE "APPROVAL" ADD CONSTRAINT "FK_DOC_CATEGORY_TO_APPROVAL_1" FOREIGN KEY (
  "DOC_CATEGORY_NO"
)
REFERENCES "DOC_CATEGORY" (
  "DOC_CATEGORY_NO"
);



-- 템플릿 제목 컬럼 추가
ALTER TABLE "APPROVAL" ADD "APPROVAL_DOC_TITLE" NVARCHAR2(50) NOT NULL;
COMMENT ON COLUMN "APPROVAL"."APPROVAL_DOC_TITLE" IS '전자결재 내부 문서 제목';
COMMIT;


-- 전자결재 관련 시퀀스 생성 ==================================================================

-- 전자결재 APPROVAL_NO SEQ 생성
CREATE SEQUENCE SEQ_APPROVAL_NO NOCACHE;

-- 결재문서 첨부파일 파일번호 APPROVAL_FILE_NO_SEQ 생성
CREATE SEQUENCE SEQ_APPROVAL_FILE_NO NOCACHE;

-- 결재자 리스트 APPROVER_NO_SEQ 생성
CREATE SEQUENCE SEQ_APPROVER_NO NOCACHE;

-- 발주 번호 시퀀스 생성 예정..
--CREATE SEQUENCE SEQ_DOC_ORDER_NO NOCACHE;

COMMIT;



-- 문서분류 데이터 생성 ==================================================================

SELECT * FROM "DOC_CATEGORY";

INSERT INTO "DOC_CATEGORY" VALUES(0, NULL, '복무', '휴가');
INSERT INTO "DOC_CATEGORY" VALUES(1, NULL, '인사', '퇴직');
INSERT INTO "DOC_CATEGORY" VALUES(2, NULL, '업무', '출점');
INSERT INTO "DOC_CATEGORY" VALUES(3, NULL, '업무', '폐점');
INSERT INTO "DOC_CATEGORY" VALUES(4, NULL, '업무', '지출');
INSERT INTO "DOC_CATEGORY" VALUES(5, NULL, '업무', '발주');

COMMIT;



-- 템플릿 info 조회 
SELECT MEMBER_NAME, TEAM_NAME
FROM "MEMBER"
JOIN "TEAM" USING(TEAM_NO)
WHERE MEMBER_NO = 9;







