-- 유진 sql

-- 전자결재 문서 APPROVAL
-- 전자결재 문서 APPROVAL_NO SEQ 생성
CREATE SEQUENCE SEQ_APPROVAL_NO NOCACHE;

COMMIT;

-- 문서분류 테이블 수정을 위한 DROP+CREATE 

DROP TABLE "DOC_CATEGORY" CASCADE CONSTRAINTS;

CREATE TABLE "DOC_CATEGORY" ( 
	"DOC_CATEGORY_NO"	NUMBER		NOT NULL,
	"DOC_HTML_NAME"	NVARCHAR2(50)		NULL,
	"DOC_CATEGORY_GROUP"	NVARCHAR2(10)		NOT NULL,
	"DOC_CATEGORY_SORT"	NVARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "DOC_CATEGORY"."DOC_CATEGORY_NO" IS '0: 복무-휴가, 1: 인사-퇴직, 2: 업무-출점, 3: 업무-폐점, 4: 업무-지출, 5: 업무-발주';

COMMENT ON COLUMN "DOC_CATEGORY"."DOC_CATEGORY_GROUP" IS '복무/인사/업무';

COMMENT ON COLUMN "DOC_CATEGORY"."DOC_CATEGORY_SORT" IS '휴가/퇴직/출점/폐점/지출/발주';

ALTER TABLE "DOC_CATEGORY" ADD CONSTRAINT "PK_DOC_CATEGORY" PRIMARY KEY (
	"DOC_CATEGORY_NO"
);

ALTER TABLE "APPROVAL" ADD CONSTRAINT "FK_DOC_CATEGORY_TO_APPROVAL_1" FOREIGN KEY (
	"DOC_CATEGORY_NO"
)
REFERENCES "DOC_CATEGORY" (
	"DOC_CATEGORY_NO"
);





