
CREATE SEQUENCE SEQ_GOODS_NO NOCACHE;

INSERT INTO "GOODS"
VALUES (SEQ_GOODS_NO.NEXTVAL, '맛이따', '낱개', 1, 1);

ROLLBACK;

SELECT LCATEGORY_NO FROM LCATEGORY WHERE LCATEGORY_NAME = '아이스크림';

ORDER BY DESC;

DELETE FROM GOODS
WHERE GOODS_NO = 17;

UPDATE "GOODS" 
JOIN LCATEGORY USING("LCATEGORY_NO")
JOIN SCATEGORY USING("SCATEGORY_NO")
SET
	GOODS_NAME = '도시락',
	GOODS_STANDARD = DEFAULT,
	LCATEGORY_NAME = '간편식사',
	SCATEGORY_NAME = '도시락'
WHERE GOODS_NO = 25;
