/* 회원가입 시 시퀀스 넘버 생성 */
CREATE SEQUENCE SEQ_MEMBER_NO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 99999
NOCYCLE
NOCACHE
NOORDER;

COMMIT;

/* 관리자 계정 추가 */
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', 'admin01', 'admin@admin.com', '관리자1', '04540^^^서울시 중구 남대문로 120^^^2층',
'01012341234', NULL, 0, DEFAULT, DEFAULT, 8, 3, 5);

SELECT * FROM "MEMBER";



		 SELECT MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_EMAIL, MEMBER_NAME, MEMBER_ADDRESS,
		 MEMBER_TEL, MEMBER_PROFILE, MEMBER_AUTHORITY, 
		 	TO_CHAR(MEMBER_ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') ENROLL_DATE
		 FROM "MEMBER"
		 WHERE MEMBER_DEL_FL = 'N'
		 AND MEMBER_ID = 'admin';
-- 부서 코드 인서트
INSERT INTO DEPARTMENT
VALUES (1, '인사관리부');

INSERT INTO DEPARTMENT
VALUES (2, '경영관리부');

INSERT INTO DEPARTMENT
VALUES (3, '운영관리부');

INSERT INTO DEPARTMENT
VALUES (4, '고객관리부');

INSERT INTO DEPARTMENT
VALUES (5, '점주');

INSERT INTO DEPARTMENT
VALUES (0, '임원부');

SELECT * FROM DEPARTMENT ;
COMMIT;

DELETE FROM DEPARTMENT d ;



-- 팀 코드 인서트

DELETE FROM TEAM t ;

INSERT INTO TEAM
VALUES (0, '임원팀');
INSERT INTO TEAM
VALUES (1, '사원관리팀');
INSERT INTO TEAM
VALUES (2, '점주관리팀');
INSERT INTO TEAM
VALUES (3, '점포관리팀');

INSERT INTO TEAM
VALUES (4, '재고관리팀');
INSERT INTO TEAM
VALUES (5, '매출관리팀');
INSERT INTO TEAM
VALUES (6, '회계팀');
INSERT INTO TEAM
VALUES (7, '영업팀');

INSERT INTO TEAM
VALUES (8, '전산팀');

INSERT INTO TEAM
VALUES (9, '행정팀');

INSERT INTO TEAM
VALUES (10, '고객서비스팀');

INSERT INTO TEAM
VALUES (11, '점포');



SELECT * FROM TEAM ;



INSERT INTO GRADE g 
VALUES (0, '사장');
INSERT INTO GRADE
VALUES (1, '부사장');
INSERT INTO GRADE
VALUES (2, '부장');
INSERT INTO GRADE
VALUES (3, '팀장');

INSERT INTO GRADE
VALUES (4, '대리');
INSERT INTO GRADE
VALUES (5, '사원');
INSERT INTO GRADE
VALUES (6, '점주');


